[project]
name = "defi-contracts"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/Users/callummcintyre/.clarinet/cache"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.beanstalk-exchange]
path = "contracts/beanstalk-exchange.clar"

[contracts.magic-beans]
path = "contracts/magic-beans.clar"

[contracts.magic-beans-lp]
path = "contracts/magic-beans-lp.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
